version: "3"

services:
  batcher:
    environment:
      - "TRACING=1"
      - "CYPHERNODE_URL=https://gatekeeper:${GATEKEEPER_PORT}"
    image: cyphernode/batcher:v0.1.0-rc.1
    entrypoint: ["npm", "run", "start:dev"]
    volumes:
      - "$APP_SCRIPT_PATH/data:/batcher/data"
      - "$GATEKEEPER_DATAPATH/certs/cert.pem:/batcher/cert.pem:ro"
      - "$LOGS_DATAPATH:/batcher/logs"
    networks:
      - cyphernodeappsnet
    restart: always
    labels:
      - "traefik.docker.network=cyphernodeappsnet"
      - "traefik.frontend.rule=PathPrefixStrip:/batcher"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.enable=true"
      - "traefik.port=8000"
      - "traefik.frontend.auth.basic.users=<username:bcrypt>"
networks:
  cyphernodeappsnet:
    external: true
