version: "3"

services:
  cyphernode_welcome:
    environment:
      - "CYPHERNODE_URL=$GATEKEEPER_URL"
      - "CYPHERNODE_CERT=/certs/cert.pem"
      - "APP_DESCRIPTION_FILE=/data/app.json"
      - "CONFIG_FILE=/data/config.toml"
    image: cyphernode/app_welcome:v0.2.2
    volumes:
      - "$GATEKEEPER_CERTS_PATH:/certs"
      - "$APP_DATA:/data"
    networks:
      - cyphernodeappsnet
    restart: always
    labels:
      - "traefik.docker.network=cyphernodeappsnet"
      - "traefik.frontend.rule=PathPrefixStrip:/welcome"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.auth.basic.usersFile=/htpasswd/htpasswd"
networks:
  cyphernodeappsnet:
    external: true
