version: "3"

services:
  cyphernode_welcome:
    environment:
      - "TRACING=1"
      - "CYPHERNODE_URL=https://gatekeeper:${GATEKEEPER_PORT}"
    image: cyphernode/app_welcome:v0.2.2
    volumes:
      - "$GATEKEEPER_CERT_FILE:/data/cert.pem"
      - "$APP_DATA/config.toml:/data/config.toml"
    networks:
      - cyphernodeappsnet
    restart: always
    labels:
      - "traefik.docker.network=cyphernodeappsnet"
      - "traefik.frontend.rule=PathPrefixStrip:/welcome"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.auth.basic.usersFile=/htpasswd/htpasswd"
networks:
  cyphernodeappsnet:
    external: true
