version: "3"

services:
  cyphernode_sparkwallet:
    command: --no-tls
    image: cyphernode/sparkwallet:v0.2.8
    volumes:
      - "$CLIGHTNING_RPC_SOCKET:/etc/lightning/lightning-rpc"
      - "$APP_DATA/cookie:/data/spark/cookie"
    labels:
      - "traefik.docker.network=cyphernodeappsnet"
      - "traefik.frontend.redirect.regex=^(.*)/sparkwallet$$"
      - "traefik.frontend.redirect.replacement=$$1/sparkwallet/"
      - "traefik.frontend.rule=PathPrefix:/sparkwallet;ReplacePathRegex: ^/sparkwallet/(.*) /$$1"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.auth.basic.usersFile=/htpasswd/htpasswd"
      - "traefik.frontend.headers.customRequestHeaders=X-Access:FoeDdQw5yl7pPfqdlGy3OEk/txGqyJjSbVtffhzs7kc="
      - "traefik.enable=true"
      - "traefik.port=9737"
    networks:
      - cyphernodeappsnet
    restart: always
networks:
  cyphernodeappsnet:
    external: true

