version: "3"

services:
  cyphernode_sparkwallet:
    command: --no-tls ${TOR_PARAMS}
    image: cyphernode/sparkwallet:v0.2.17
    environment:
      - "NETWORK=${NETWORK}"
    volumes:
      - "$LIGHTNING_DATAPATH/:/etc/lightning"
      - "$APP_SCRIPT_PATH/cookie:/data/spark/cookie"
      - "$GATEKEEPER_DATAPATH/htpasswd:/htpasswd/htpasswd"
    labels:
      - "traefik.docker.network=cyphernodeappsnet"
      - "traefik.frontend.entryPoints=https"
      - "traefik.frontend.redirect.regex=^(.*)/sparkwallet$$"
      - "traefik.frontend.redirect.replacement=$$1/sparkwallet/"
      - "traefik.frontend.rule=PathPrefix:/sparkwallet;ReplacePathRegex: ^/sparkwallet/(.*) /$$1"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.auth.basic.usersFile=/htpasswd/htpasswd"
      - "traefik.frontend.headers.customRequestHeaders=X-Access:FoeDdQw5yl7pPfqdlGy3OEk/txGqyJjSbVtffhzs7kc="
      - "traefik.enable=true"
      - "traefik.port=9737"
    networks:
      - cyphernodeappsnet
    restart: always
networks:
  cyphernodeappsnet:
    external: true
